# Generated by Django 5.2.3 on 2025-06-15 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('trim', models.CharField(blank=True, max_length=100, null=True)),
                ('msrp_starting', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('msrp_average', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('engine_type', models.CharField(blank=True, max_length=100, null=True)),
                ('horsepower', models.IntegerField(blank=True, null=True)),
                ('torque', models.IntegerField(blank=True, null=True)),
                ('mpg_city', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('mpg_highway', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('drivetrain', models.CharField(blank=True, max_length=50, null=True)),
                ('body_type', models.CharField(blank=True, max_length=50, null=True)),
                ('overall_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('reliability_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('safety_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('ai_insight_summary', models.TextField(blank=True, null=True)),
                ('top_pros', models.JSONField(blank=True, null=True)),
                ('top_cons', models.JSONField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('main_image_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ['-year', 'make', 'model'],
                'unique_together': {('make', 'model', 'year', 'trim')},
            },
        ),
    ]
