# Generated by Django 5.2.3 on 2025-06-18 15:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('source_name', models.CharField(max_length=200)),
                ('source_url', models.URLField(blank=True, max_length=500, null=True)),
                ('reviewer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('reviewer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('source_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('review_date', models.DateField(blank=True, null=True)),
                ('retrieval_date', models.DateTimeField(auto_now_add=True)),
                ('sentiment_compound_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('sentiment_classification', models.CharField(blank=True, max_length=20, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='cars.car')),
            ],
            options={
                'ordering': ['-retrieval_date'],
            },
        ),
    ]
