# Generated by Django 5.2.3 on 2025-06-29 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_searchquery_carsave_carview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reviewer_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('car', 'source_name', 'reviewer_id')},
        ),
    ]
