# Generated by Django 5.2.3 on 2025-06-29 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_review_reviewer_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='source_rating',
        ),
        migrations.AddField(
            model_name='review',
            name='source_upvotes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
